import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { createTheme, StyledEngineProvider, ThemeProvider } from '@mui/material'

const theme = createTheme({
    typography: {
        fontFamily: 'Kanit',
    },
})

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>{process.env.NEXT_PUBLIC_APP_NAME}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <StyledEngineProvider injectFirst>
                <ThemeProvider theme={theme}>
                    <Component {...pageProps} />
                </ThemeProvider>
            </StyledEngineProvider>
        </>
    )
}

export default MyApp
